"""
项目名称: water-quality-classification
技术领域: 01-geospatial-remote-sensing
模块说明: shuiyu.py - 核心业务算法实现
作者: 杨佳 (资深 AI 算法与遥感工程师)
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shuiyu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(537, 420)
        self.getimgfiles_button = QtWidgets.QPushButton(Dialog)
        self.getimgfiles_button.setGeometry(QtCore.QRect(10, 90, 521, 23))
        self.getimgfiles_button.setObjectName("getimgfiles_button")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 120, 521, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.openImgFile_dftablewidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.openImgFile_dftablewidget.setGeometry(QtCore.QRect(0, 20, 521, 51))
        self.openImgFile_dftablewidget.setObjectName("openImgFile_dftablewidget")
        self.openImgFile_dftablewidget.setColumnCount(0)
        self.openImgFile_dftablewidget.setRowCount(0)
        self.export_vector_button = QtWidgets.QPushButton(Dialog)
        self.export_vector_button.setGeometry(QtCore.QRect(10, 380, 521, 23))
        self.export_vector_button.setObjectName("export_vector_button")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 290, 521, 81))
        self.groupBox.setObjectName("groupBox")
        self.process_dftablewidget = QtWidgets.QTableWidget(self.groupBox)
        self.process_dftablewidget.setGeometry(QtCore.QRect(0, 20, 521, 51))
        self.process_dftablewidget.setObjectName("process_dftablewidget")
        self.process_dftablewidget.setColumnCount(0)
        self.process_dftablewidget.setRowCount(0)
        self.starat_classify_button = QtWidgets.QPushButton(Dialog)
        self.starat_classify_button.setGeometry(QtCore.QRect(10, 260, 521, 23))
        self.starat_classify_button.setObjectName("starat_classify_button")
        self.geomode_radiobutton = QtWidgets.QRadioButton(Dialog)
        self.geomode_radiobutton.setGeometry(QtCore.QRect(20, 40, 261, 16))
        self.geomode_radiobutton.setObjectName("geomode_radiobutton")
        self.normmode_radiobutton = QtWidgets.QRadioButton(Dialog)
        self.normmode_radiobutton.setGeometry(QtCore.QRect(280, 40, 241, 16))
        self.normmode_radiobutton.setObjectName("normmode_radiobutton")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 521, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 501, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.qingdan_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.qingdan_2.setContentsMargins(0, 0, 0, 0)
        self.qingdan_2.setObjectName("qingdan_2")
        self.getimgtype_button_2 = QtWidgets.QGroupBox(Dialog)
        self.getimgtype_button_2.setGeometry(QtCore.QRect(10, 200, 521, 51))
        self.getimgtype_button_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.getimgtype_button_2.setObjectName("getimgtype_button_2")
        self.selectmodelfile_button = QtWidgets.QPushButton(self.getimgtype_button_2)
        self.selectmodelfile_button.setGeometry(QtCore.QRect(0, 20, 261, 23))
        self.selectmodelfile_button.setObjectName("selectmodelfile_button")
        self.label_2 = QtWidgets.QLabel(self.getimgtype_button_2)
        self.label_2.setGeometry(QtCore.QRect(310, 20, 111, 21))
        self.label_2.setObjectName("label_2")
        self.setimgsize_ledit = QtWidgets.QLineEdit(self.getimgtype_button_2)
        self.setimgsize_ledit.setEnabled(True)
        self.setimgsize_ledit.setGeometry(QtCore.QRect(430, 20, 41, 21))
        self.setimgsize_ledit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.setimgsize_ledit.setAutoFillBackground(False)
        self.setimgsize_ledit.setText("")
        self.setimgsize_ledit.setObjectName("setimgsize_ledit")
        self.groupBox_3.raise_()
        self.getimgfiles_button.raise_()
        self.groupBox_2.raise_()
        self.export_vector_button.raise_()
        self.groupBox.raise_()
        self.starat_classify_button.raise_()
        self.geomode_radiobutton.raise_()
        self.normmode_radiobutton.raise_()
        self.getimgtype_button_2.raise_()

        self.retranslateUi(Dialog)
        self.getimgfiles_button.clicked.connect(Dialog.openImgPath)
        self.export_vector_button.clicked.connect(Dialog.export_vector)
        self.starat_classify_button.clicked.connect(Dialog.water_classify_pro)
        self.normmode_radiobutton.clicked.connect(Dialog.getImgType)
        self.geomode_radiobutton.clicked.connect(Dialog.getImgType)
        self.selectmodelfile_button.clicked.connect(Dialog.selectModelFile)
        self.setimgsize_ledit.textChanged['QString'].connect(Dialog.setImgSize_slcet)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.getimgfiles_button.setText(_translate("Dialog", "导入图像"))
        self.groupBox_2.setTitle(_translate("Dialog", "导入图像清单"))
        self.export_vector_button.setText(_translate("Dialog", "栅格镶嵌/矢量合并"))
        self.groupBox.setTitle(_translate("Dialog", "水域分割进度"))
        self.starat_classify_button.setText(_translate("Dialog", "开始水域分割（耗时较长，请耐心等待！完成进度框会跳出提示）"))
        self.geomode_radiobutton.setText(_translate("Dialog", "完整坐标影像识别"))
        self.normmode_radiobutton.setText(_translate("Dialog", "无坐标影像识别"))
        self.groupBox_3.setTitle(_translate("Dialog", "模式选择"))
        self.getimgtype_button_2.setTitle(_translate("Dialog", "模型参数定义"))
        self.selectmodelfile_button.setText(_translate("Dialog", "选择模型"))
        self.label_2.setText(_translate("Dialog", "设置切割图像大小："))
        self.setimgsize_ledit.setPlaceholderText(_translate("Dialog", "2048"))
