from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT_DIR = Path(r"E:\PY\LSTM\0401")
MODEL_DIR = ROOT_DIR / "models" / "current_confirmed_models"
DATA_DIR = ROOT_DIR / "data" / "generated"
RESULT_DIR = ROOT_DIR / "results"
RUNTIME_DIR = ROOT_DIR / "runtime_ascii"

# Current final test templates confirmed by the user:
# 1) the truth event model is the historical no-flooding 0.3x three-point injection case
# 2) the baseline model is generated by removing those three injections from the truth model
BASELINE_MODEL_INP = MODEL_DIR / "0327_由真值模型去注水重建_旱天基线模型_10分钟_泵站0.5开0.2关.inp"
BASELINE_MODEL_OUT = MODEL_DIR / "0327_由真值模型去注水重建_旱天基线模型_10分钟_泵站0.5开0.2关.out"
BASELINE_MODEL_RPT = MODEL_DIR / "0327_由真值模型去注水重建_旱天基线模型_10分钟_泵站0.5开0.2关.rpt"

TRUTH_EVENT_MODEL_INP = MODEL_DIR / "0327_由旱天基线重建_三点注水模型_0.3倍.inp"
TRUTH_EVENT_MODEL_OUT = MODEL_DIR / "0327_由旱天基线重建_三点注水模型_0.3倍.out"
TRUTH_EVENT_MODEL_RPT = MODEL_DIR / "0327_由旱天基线重建_三点注水模型_0.3倍.rpt"

LAYOUT_HTML = MODEL_DIR / "0401_布设方案可视化.html"
LAYOUT_NODE_CSV = MODEL_DIR / "0401_布设方案节点表.csv"
LAYOUT_LINK_CSV = MODEL_DIR / "0401_布设方案连接表.csv"
LAYOUT_SUMMARY_JSON = MODEL_DIR / "0401_布设方案说明.json"

TOTAL_PROCESS_CSV = DATA_DIR / "0401_总入流过程_10分钟.csv"
TRUTH_INJECTION_CSV = DATA_DIR / "0401_真值注水数据_10分钟.csv"
BASELINE_MONITOR_CSV = DATA_DIR / "0401_基线监测_10分钟.csv"
EVENT_MONITOR_CSV = DATA_DIR / "0401_事件监测_10分钟.csv"
OBSERVED_DELTA_CSV = DATA_DIR / "0401_观测增量_10分钟.csv"
OUTLET_SERIES_CSV = DATA_DIR / "0401_排口过程_10分钟.csv"
DATA_SUMMARY_JSON = DATA_DIR / "0401_数据构造汇总.json"

SMALL_RESULT_DIR = RESULT_DIR / "small_run"
ASCII_BASELINE_TEMPLATE = RUNTIME_DIR / "baseline_template.inp"

CANDIDATE_NODES = (
    "J193",
    "J70",
    "J71",
    "J74",
    "J76",
    "J78",
    "J81",
    "J85",
    "J89",
    "J41",
    "J120",
    "J124",
    "J125",
    "J129",
    "J131",
    "J135",
    "J137",
    "J140",
    "J145",
    "J67",
)

MONITOR_NODES = ("J74", "J77", "J78", "J123", "J126", "J141", "J139", "J145", "J231")
TRUTH_INJECTION_NODES = ("J76", "J124", "J140")
OUTFALL_NODE = "J132"
TERMINAL_NODE = "J231"
STEP_MINUTES = 10
STEP_SECONDS = STEP_MINUTES * 60


@dataclass(frozen=True)
class ExperimentConfig:
    ga_population_count: int = 2
    ga_population_size: int = 8
    ga_generations: int = 4
    ga_elite_ratio: float = 0.25
    ga_mutation_strength: float = 0.18
    ga_migration_interval: int = 2
    ga_migration_count: int = 2
    ga_competition_replace_count: int = 2
    am_chain_count: int = 2
    am_samples_per_chain: int = 60
    am_warmup: int = 15
    am_adapt_start: int = 15
    am_initial_covariance: float = 0.002
    am_eps: float = 1e-8
    posterior_validation_samples: int = 12
    parallel_workers: int = 4
    random_seed: int = 20260401
    progress_step_interval: int = 10


def ensure_dirs() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    SMALL_RESULT_DIR.mkdir(parents=True, exist_ok=True)
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)


def runtime_model_path(worker_id: int) -> Path:
    worker_dir = RUNTIME_DIR / f"worker_{worker_id}"
    worker_dir.mkdir(parents=True, exist_ok=True)
    target = worker_dir / "model.inp"
    if (not target.exists()) or target.stat().st_mtime < BASELINE_MODEL_INP.stat().st_mtime:
        target.write_bytes(BASELINE_MODEL_INP.read_bytes())
    return target
